# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd3dac7b2ec7d323416e2ae2d42bb90286c5f171bbcb3fcad2195eea10cbb8a09d1e354bac4e85726e78ffa908edf48a5cdbf14e889532e3a5e04d021059c753

test:
  secret_key_base: fad407ac6d99ca3637dbb1bea205ff80c30820f38d53eaea6a67d52e49606c431bf7764f491a689d5786f2ec1f35ec7123781ee583a4ad4b1e6e84e609d8edf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
